### ISSUE TITLE
`image-info` fails to inspect LVM on RHEL-9.1 GA and c9s

### ISSUE THREAD

**Issue by thozza** [osbuild/manifest-db#75]
```
centos_9-aarch64-qcow2_customize-boot Building & Comparing: FAIL: image-info failed: Traceback (most recent call last):
  File "/home/centos/~/builds/redhat/services/products/image-builder/ci/osbuild/manifest-db/tools/image-info", line 2742, in <module>
    main()
  File "/home/centos/~/builds/redhat/services/products/image-builder/ci/osbuild/manifest-db/tools/image-info", line 2736, in main
    report = analyse_image(target)
  File "/home/centos/~/builds/redhat/services/products/image-builder/ci/osbuild/manifest-db/tools/image-info", line 2596, in analyse_image
    append_partitions(report, device, loctl)
  File "/home/centos/~/builds/redhat/services/products/image-builder/ci/osbuild/manifest-db/tools/image-info", line 2528, in append_partitions
    lvm = cm.enter_context(discover_lvm(dev))
  File "/usr/lib64/python3.9/contextlib.py", line 448, in enter_context
    result = _cm_type.__enter__(cm)
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/centos/~/builds/redhat/services/products/image-builder/ci/osbuild/manifest-db/tools/image-info", line 2461, in discover_lvm
    raise RuntimeError(r.stderr.strip())
RuntimeError: b'WARNING: Not using device /dev/loop0p3 for PV 1BrGW4-bbcH-G9gI-hdgM-Dnyd-VywX-2WJwIM.\n  WARNING: PV 1BrGW4-bbcH-G9gI-hdgM-Dnyd-VywX-2WJwIM prefers device /dev/loop1 because device was seen first.\n  Cannot activate LVs in VG rootvg while PVs appear on duplicate devices.\n  Cannot activate LVs in VG rootvg while PVs appear on duplicate devices.'
```

**Comment by lavocatt** [comment]
This is fixed now :partying_face:
